mysite/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     url(r'^polls/', include('polls.urls', namespace="polls")),
     url(r'^admin/', include(admin.site.urls)),
)

polls/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from polls import views

urlpatterns = patterns('',
    url(r'^login/$', views.loginView, name='login'),
    url(r'^logout/$', views.logoutView, name='logout'),
    url(r'^$', login_required(views.IndexView.as_view()), name='index'),
    url(r'^(?P<pk>\d+)/$', login_required(views.DetailView.as_view()), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', login_required(views.ResultsView.as_view()), name='results'),
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

polls/models.py
import datetime
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User

class Poll(models.Model):

    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    start_time = models.DateTimeField('start time')
    end_time = models.DateTimeField('end time')

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.question

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <  now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):

    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.choice_text

class Vote(models.Model):
    
    user = models.ForeignKey(User)
    poll = models.ForeignKey(Poll)
    choice = models.ForeignKey(Choice)

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.views import generic
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils import timezone

from polls.models import Choice, Poll, Vote

def loginView(request):
    username = request.POST.get('username', None)
    password = request.POST.get('password', None)
    if username is not None and password is not None:
        user = authenticate(username = username, password = password)
        if user is not None and user.is_active:
            login(request, user)
            return redirect('polls:index')
        else:
            # Login failed
            return HttpResponse('Username/password combo is incorrect.')
    else:
        # Render the login form
        return render(request, 'polls/login.html', locals())

def logoutView(request):
    logout(request)
    return redirect('polls:index')

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_poll_list'

    def get_queryset(self):
        """
        Return the last five published polls.
        """
        now = timezone.now()
        polls = Poll.objects.filter(start_time__lte = now, end_time__gte = now, 
                                    pub_date__lte = now) \
                            .order_by('-pub_date')[:5]
        return polls

class DetailView(generic.DetailView):
    model = Poll
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Filter out the polls that are off
        """
        now = timezone.now()
        return Poll.objects.filter(start_time__lte = now, end_time__gte = now)

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['has_voted'] = Vote.objects.filter(user = self.request.user, 
                                                   poll = self.get_object()) \
                                           .exists()
        return context

class ResultsView(generic.DetailView):
    model = Poll
    template_name = 'polls/results.html'

    def get_queryset(self):
        """
        Filter out the polls that are off
        """
        now = timezone.now()
        return Poll.objects.filter(start_time__lte = now, end_time__gte = now)

@login_required(login_url='polls:login')
def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    now = timezone.now()
    if not (p.start_time <= now and p.end_time >= now):
        return redirect('polls:index')
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the poll voting form.
        return render(request, 'polls/detail.html', {
            'poll': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        vote = Vote(user = request.user, poll = p, choice = selected_choice)
        vote.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

polls/templates/polls/detail.html
<!DOCTYPE html>
<html>
<head>
    <title>Welcome to Polls Central</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
</head>
<body>

<h1>{{ poll.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' poll.id %}" method="post">
{% csrf_token %}
{% for choice in poll.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
{% if has_voted %}
<br />
<label>You have already voted for this poll, thanks for your participation!</label>
<br />
<a href="{% url 'polls:results' poll.id %}">See results</a>
{% else %}
<input type="submit" value="Vote" />
{% endif %}
</form>

<a href="{% url 'polls:index' %}">Back to Polls list</a>
<a href="{% url 'polls:logout' %}">Log Out</a>

</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Welcome to Polls Central</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
</head>
<body>

{% if latest_poll_list %}
    <ul>
    {% for poll in latest_poll_list %}
        <li><a href="{% url 'polls:detail' poll.id %}">{{ poll.question }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<a href="{% url 'polls:logout' %}">Log Out</a>
</body>
</html>

polls/templates/polls/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Poll System Login</title>
</head>
<body>
    <h1>Login</h1>
    <form action="{% url 'polls:login' %}" method="POST">
        <label>Username</label>
        <input type="text" name="username" />
        <br />
        <label>Password</label>
        <input type="password" name="password" />
        <br />
        <input type="submit" value="Login" />
        {% csrf_token %}
    </form>
</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html>
<head>
    <title>Welcome to Polls Central</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
</head>
<body>

<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:index' %}">Back to Polls list</a>
<a href="{% url 'polls:logout' %}">Log Out</a>

</body>
</html>